## Instructions

#### 。 This homework has two parts
    1. There are 6 simple questions, just follow the instrctions and get the same output as the following.
    2. It's how simple neural networks working. As the same as part 1, just follow the instructions and get the same output

#### 。 All of this homework should use Numpy or Pandas

#### 。 Please follow the same variable name as the instuctions of every questions 

## Part 1

**1. Import both numpy and pandas packages**

In [5]:
import pandas as pd
import numpy as np

**2. Create a 3x3 matrix with values ranging from 0 to 8**

In [6]:
a1=np.array([[0,1,2],[3,4,5],[6,7,8]])
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**3. Create a 5x5 matrix with row values ranging from 0 to 4**

In [7]:
b=np.full((5,5),[0.,1.,2.,3.,4.])
b

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

**4. How to swap the first and second rows of a**

In [8]:
a = np.arange(25).reshape(5,5)


**5. Give two ways to show how to get the n largest values of a (no sort the value is fine)**

In [9]:
# Don't need to change this cell
a = np.arange(100)
np.random.shuffle(a)
n = 5

In [10]:
# Way 1
max_index=np.argpartition(a,-n)[-n:]
print(list(a[max_index]))

[95, 96, 97, 99, 98]


In [11]:
# Way 2
a.sort()
print(a[99],a[98],a[97],a[96],a[95])

99 98 97 96 95


**6. Compare if array a and array b is totally the same**

In [43]:
np.random.seed(123)
a = np.round(np.random.random(100)*100, 0)
b = np.random.randint(1, 100, 100)
compare=list(a==b)
if False in compare:
    print("False")

False


## Part 2

### Online Shoppers Purchasing Intention Dataset

The dataset consists of 10 numerical and 8 categorical attributes. The 'Revenue' attribute can be used as the class label.

* ``0 Administrative``, ``1 Administrative Duration``, ``2 Informational``, ``3 Informational Duration``, ``4 Product Related`` and ``5 Product Related Duration`` - represent the number of different types of pages visited by the visitor in that session and total time spent in each of these page categories. The values of these features are derived from the URL information of the pages visited by the user and updated in real time when a user takes an action, e.g. moving from one page to another. 


* ``6 Bounce Rate``, ``7 Exit Rate`` and ``8 Page Value`` - represent the metrics measured by "Google Analytics" for each page in the e-commerce site. The value of "Bounce Rate" feature for a web page refers to the percentage of visitors who enter the site from that page and then leave ("bounce") without triggering any other requests to the analytics server during that session. The value of "Exit Rate" feature for a specific web page is calculated as for all pageviews to the page, the percentage that were the last in the session. The "Page Value" feature represents the average value for a web page that a user visited before completing an e-commerce transaction. 


* ``9 Special Day`` - indicates the closeness of the site visiting time to a specific special day (e.g. Mother’s Day, Valentine's Day) in which the sessions are more likely to be finalized with transaction. The value of this attribute is determined by considering the dynamics of e-commerce such as the duration between the order date and delivery date. For example, for Valentina’s day, this value takes a nonzero value between February 2 and February 12, zero before and after this date unless it is close to another special day, and its maximum value of 1 on February 8. 


* The dataset also includes ``11 operating system``, ``12 browser``, ``13 region``, ``14 traffic type``, ``15 visitor type`` as returning or new visitor, a Boolean value indicating whether the date of the visit is ``16 weekend``, and ``9 month of the year``.


---
* **``17 Revenue``** - binary labels



* More information of this data: [UCI | Online Shoppers Purchasing Intention Dataset](https://archive.ics.uci.edu/ml/datasets/Online+Shoppers+Purchasing+Intention+Dataset#)

**Use pandas to import the data and check the shape of dataset and save it as `" shoppers "`**

In [13]:
online_shoppers_intention=pd.read_csv("online_shoppers_intention.csv")
shoppers = (online_shoppers_intention.shape[0],online_shoppers_intention.shape[1])
print(shoppers)

(12330, 18)


**Use pandas function to let label be numeric as below and save it as `" label "`**

In [14]:
Revenue=online_shoppers_intention["Revenue"]
# print(Revenue)
label_list = []
for i in Revenue:
    if i == False:
        label_list.append(0)
    if i ==True:
        label_list.append(1)
label=np.array(label_list)
label=np.int8(label)
label

array([0, 0, 0, ..., 0, 0, 0], dtype=int8)

**See some information of this data**

In [15]:
online_shoppers_intention.head()

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   
2               0                      0.0              0   
3               0                      0.0              0   
4               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                     0.0               1                 0.000000   
1                     0.0               2                64.000000   
2                     0.0               1                 0.000000   
3                     0.0               2                 2.666667   
4                     0.0              10               627.500000   

   BounceRates  ExitRates  PageValues  SpecialDay Month  OperatingSystems  \
0         0.20       0.20         0.0         0.0   Feb                 1   
1         0.00       0.10         0.0         0.0   Feb                 2   
2         0.20       0.20         0.0         0.0   Feb                 4   
3         0.05       0.14         0.0         0.0   Feb                 3   
4         0.02       0.05         0.0         0.0   Feb                 3   

   Browser  Region  TrafficType        VisitorType  Weekend  Revenue  
0        1       1            1  Returning_Visitor    False    False  
1        2       1            2  Returning_Visitor    False    False  
2        1       9            3  Returning_Visitor    False    False  
3        2       2            4  Returning_Visitor    False    False  
4        3       1            4  Returning_Visitor     True    False

In [16]:
df=pd.DataFrame({"count":online_shoppers_intention.count(numeric_only=True),"mean":online_shoppers_intention.mean(numeric_only=True),"std":online_shoppers_intention.std(numeric_only=True),"min":online_shoppers_intention.min(numeric_only=True),"25%":online_shoppers_intention.quantile(0.25,numeric_only=True),"50%":online_shoppers_intention.median(),"75%":online_shoppers_intention.quantile(0.75,numeric_only=True),"max":online_shoppers_intention.max(numeric_only=True)})
# df=df.dropna()
df=df.drop(["Revenue","Weekend"])
df=df.transpose()
df

C:\Users\YUCHEN~1\AppData\Local\Temp/ipykernel_10544/3350573821.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df=pd.DataFrame({"count":online_shoppers_intention.count(numeric_only=True),"mean":online_shoppers_intention.mean(numeric_only=True),"std":online_shoppers_intention.std(numeric_only=True),"min":online_shoppers_intention.min(numeric_only=True),"25%":online_shoppers_intention.quantile(0.25,numeric_only=True),"50%":online_shoppers_intention.median(),"75%":online_shoppers_intention.quantile(0.75,numeric_only=True),"max":online_shoppers_intention.max(numeric_only=True)})


Administrative Administrative_Duration Informational  \
count          12330                   12330         12330   
mean        2.315166               80.818611      0.503569   
std         3.321784              176.779107      1.270156   
min                0                     0.0             0   
25%              0.0                     0.0           0.0   
50%              1.0                     7.5           0.0   
75%              4.0                93.25625           0.0   
max               27                 3398.75            24   

      Informational_Duration ProductRelated ProductRelated_Duration  \
count                  12330          12330                   12330   
mean               34.472398      31.731468              1194.74622   
std               140.749294      44.475503             1913.669288   
min                      0.0              0                     0.0   
25%                      0.0            7.0                184.1375   
50%                      0.0           18.0              598.936905   
75%                      0.0           38.0             1464.157214   
max                 2549.375            705             63973.52223   

      BounceRates ExitRates  PageValues SpecialDay OperatingSystems   Browser  \
count       12330     12330       12330      12330            12330     12330   
mean     0.022191  0.043073    5.889258   0.061427         2.124006  2.357097   
std      0.048488  0.048597   18.568437   0.198917         0.911325  1.717277   
min           0.0       0.0         0.0        0.0                1         1   
25%           0.0  0.014286         0.0        0.0              2.0       2.0   
50%      0.003112  0.025156         0.0        0.0              2.0       2.0   
75%      0.016813      0.05         0.0        0.0              3.0       2.0   
max           0.2       0.2  361.763742        1.0                8        13   

         Region TrafficType  
count     12330       12330  
mean   3.147364    4.069586  
std    2.401591    4.025169  
min           1           1  
25%         1.0         2.0  
50%         3.0         2.0  
75%         4.0         4.0  
max           9          20

**Choose column [1, 4, 5, 11, 12, 13] and turn into numpy array ``" x "``**

In [17]:
x=np.array([online_shoppers_intention.iloc[0]["Administrative_Duration"],online_shoppers_intention.iloc[0]["ProductRelated"],online_shoppers_intention.iloc[0]["ProductRelated_Duration"],online_shoppers_intention.iloc[0]["OperatingSystems"],online_shoppers_intention.iloc[0]["Browser"],online_shoppers_intention.iloc[0]["Region"]])
for i in range(1,len(online_shoppers_intention)):
    y=np.array([online_shoppers_intention.iloc[i]["Administrative_Duration"],online_shoppers_intention.iloc[i]["ProductRelated"],online_shoppers_intention.iloc[i]["ProductRelated_Duration"],online_shoppers_intention.iloc[i]["OperatingSystems"],online_shoppers_intention.iloc[i]["Browser"],online_shoppers_intention.iloc[i]["Region"]])
    x=np.vstack((x,y))
print(x.shape)

(12330, 6)


In [18]:
x

array([[  0.  ,   1.  ,   0.  ,   1.  ,   1.  ,   1.  ],
       [  0.  ,   2.  ,  64.  ,   2.  ,   2.  ,   1.  ],
       [  0.  ,   1.  ,   0.  ,   4.  ,   1.  ,   9.  ],
       ...,
       [  0.  ,   6.  , 184.25,   3.  ,   2.  ,   1.  ],
       [ 75.  ,  15.  , 346.  ,   2.  ,   2.  ,   3.  ],
       [  0.  ,   3.  ,  21.25,   3.  ,   2.  ,   1.  ]])

**Use numpy function to load weight data, bias data and check their shape**

In [19]:
weight_1 = np.load("layer_1_weight.npy")
weight_2 = np.load("layer_2_weight.npy")

bias_1 = np.load("layer_1_bias.npy")
bias_2 = np.load("layer_2_bias.npy")

In [20]:
print('weight_1 shape:', weight_1.shape)
print('weight_2 shape:',weight_2.shape )
print('')
print('bias_1 shape:', bias_1.shape)
print('bias_2 shape:', bias_2.shape)

weight_1 shape: (6, 32)
weight_2 shape: (32, 2)

bias_1 shape: (32,)
bias_2 shape: (2,)


**Use numpy function to compute `" x "` and weight_1 matrix multiplication, and check the shape**

In [21]:
x = np.matmul(x,weight_1)
x.shape

(12330, 32)

**Use numpy function to compute `" x "` and bias_1 matrix addtion, and check the shape**

In [22]:
x = np.add(x,bias_1)
x.shape

(12330, 32)

**Use numpy function to compute `" x "` and weight_2 matrix multiplication, and check the shape**

In [23]:
x = np.matmul(x,weight_2)
x.shape

(12330, 2)

**Use numpy function to compute `" x "` and bias_2 matrix addtion, and check the shape**

In [24]:
x = np.add(x,bias_2)
x.shape

(12330, 2)

**Check if your x is same as below**

In [25]:
x

array([[ -0.42815397,  -0.58708018],
       [ 17.76804854, -12.0093477 ],
       [ -1.07327452,  -3.72237766],
       ...,
       [ 51.70654464, -34.08445513],
       [110.52965928, -73.95802223],
       [  5.45892153,  -4.42243782]])

**Use numpy function to find out each row which one value is bigger, and save it as `" pre "`**

In [42]:
pre=np.where(x[0]==x[0].max())
for i in range(1,len(x)):
    pre1=np.where(x[i]==x[i].max())
    pre=np.append(pre,pre1)
pre

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

**Use numpy function to check if `pre[i]` is the same as `label[i]`, and save it as `" check "`**

In [48]:
compare=list(pre==label)
check_list=[]
for i in compare:
    if i ==True:
        check_list.append(1)
    elif i==False:
        check_list.append(0)
check = np.array(check_list)
check

array([1, 1, 1, ..., 1, 1, 1])

**Use numpy function to calculate the accuracy**

In [50]:
accuracy=check.sum()/check.shape
print('accuracy:',accuracy)

accuracy: [0.82846715]
